package co.system.LoginForm;

import co.system.orderManagementForm.Product_Status;
import java.awt.Color;
import java.awt.Font;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import co.system.userManagementForm.UserDashboard;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;

//LoginForm is inherited from javax.swing.JFrame
public class LoginForm extends javax.swing.JFrame {

    public LoginForm() {
        initComponents();
        
        //Setting window location to the center
        setLocationRelativeTo(null);
        
        //calling placeholder methods
        addPlaceholder(userName);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel_userIcon = new javax.swing.JLabel();
        jLabel_passIcon = new javax.swing.JLabel();
        userName = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        jLabel_Register_form = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton_login = new javax.swing.JButton();
        position = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(69, 93, 122));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Login ");

        jLabel_userIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/user.png"))); // NOI18N

        jLabel_passIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/password.png"))); // NOI18N

        userName.setText("Username");
        userName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                userNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                userNameFocusLost(evt);
            }
        });
        userName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameActionPerformed(evt);
            }
        });

        jLabel_Register_form.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_Register_form.setForeground(new java.awt.Color(51, 51, 255));
        jLabel_Register_form.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Register_form.setText("Register a new account");
        jLabel_Register_form.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Register_form.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_Register_formMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Position");

        jButton_login.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_login.setText("Login");
        jButton_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_loginActionPerformed(evt);
            }
        });

        position.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select", "Managing staff", "Delivery staff" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_userIcon)
                                    .addComponent(jLabel_passIcon))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(userName, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(position, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jButton_login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 39, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jLabel_Register_form, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel_userIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userName, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_passIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(position, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(jButton_login, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel_Register_form, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
        
    private String usernames;  
    private String passwords;
    private String positions;

        //methods to add and remove placeholder 
    
    public void addPlaceholder(JTextField textField){
        Font font = textField.getFont();
        font = font.deriveFont(Font.ITALIC); //setting font
        textField.setFont(font);
        textField.setForeground(Color.gray); //setting color
        
    }
    
    public void removePlaceholder(JTextField textField){
        Font font = textField.getFont();
        font = font.deriveFont(Font.PLAIN);
        textField.setFont(font);
        textField.setForeground(Color.black);
        
    }
    
    public int countLine(){
        int totalLine=0;
        String readLine;
        String path = "src\\File_collection\\LoginCredentials.txt";
        
        File file = new File(path);
        
        try {
            BufferedReader br = new BufferedReader(new FileReader(file));
            while((readLine=br.readLine()) != null){
                totalLine++;
            }
  
        } catch (FileNotFoundException ex) {
            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
        }
 
       return totalLine;
    }
    
    private void checkData(){
         
        
        usernames = userName.getText();
        passwords = password.getText();
        positions = position.getSelectedItem().toString();
        
//        System.out.println(usernames+passwords+positions);

        try {
            int currentLine=0;
            File file = new File("src\\File_collection\\LoginCredentials.txt");
            Scanner scan = new Scanner(file);
            scan.useDelimiter("[,\n]");
            
            while(scan.hasNext()){
               currentLine++;
               String id = scan.next();
               String user_position = scan.next();
               String user_name = scan.next();
               String user_password=scan.next();
               String user_gender=scan.next();
                
//               System.out.println(user_name+user_password+user_gender);
                
                if(positions.equalsIgnoreCase("Managing staff")){
                    if(!(usernames.equalsIgnoreCase(user_name)) || !(passwords.equalsIgnoreCase(user_password))){
                        if(countLine()==currentLine ){
                      JOptionPane.showMessageDialog(null, "no such user!","Error",JOptionPane.ERROR_MESSAGE);
                      break;
                    }
                        
                    continue;
                    
                }else{
                    
                    if(positions.equals(user_position)){
                        JOptionPane.showMessageDialog(null, "<html><b style=\"color:green; font-size:14px; \">Login Successful.</b></html>");
                        //Create an object of class "UserDashboard"
                        UserDashboard d = new UserDashboard();
                        d.setVisible(true);
                        this.setVisible(true);
                        this.setVisible(false);
                        d.setDashName(user_name);
                        if(user_name.equalsIgnoreCase("suman dangol")){
                            d.setUserImage("suman dangol");
                        }else{
                            d.setUserImage("userImage");  
                        }
                        
                        break;
                    }else {
                        JOptionPane.showMessageDialog(null, "Invalid position!","Error",JOptionPane.ERROR_MESSAGE);
                        break;
                        }                                       
                    }       
                    
                }
                 
                ///////////////
                
                if(positions.equalsIgnoreCase("Delivery staff")){
                    if(!(usernames.equalsIgnoreCase(user_name)) || !(passwords.equalsIgnoreCase(user_password))){
                        if(countLine()==currentLine ){
                            JOptionPane.showMessageDialog(null, "no such user!");
                            break;
                        }
                        
                        continue;
                }else{
                    
                    if(positions.equals(user_position)){
                        JOptionPane.showMessageDialog(null, "<html><b style=\"color:green; font-size:14px; \">Login Successful.</b></html>");
                        Product_Status deliveryStatus= new  Product_Status();
                        deliveryStatus.setVisible(true);
                        this.setVisible(true);
                        this.setVisible(false);
                        deliveryStatus.setUserName(user_name);
                        if(user_name.equalsIgnoreCase("anil kafle")){
                            deliveryStatus.setUserImage(user_name);
                        }else{
                            deliveryStatus.setUserImage("userImage");
                        }
                        
                        break;
                    }else {
                        JOptionPane.showMessageDialog(null, "Invalid position!","Error",JOptionPane.ERROR_MESSAGE);
                        break;
                    }                                       
                } 
            }
                
            if (usernames.equals("Username") || passwords.equals("")
                        ||positions.equals("select")){
                    JOptionPane.showMessageDialog(null, "Fill all the fields correctly","Error",JOptionPane.ERROR_MESSAGE);
                    break;                                          
                } 
 
            }
                
        } catch (FileNotFoundException ex) {
            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
        }

    }    
    
    
    private void userNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userNameFocusGained
        if(userName.getText().equals("Username")){
            userName.setText(null);
            userName.requestFocus();
            //remove Placeholder
            removePlaceholder(userName);
        }            
    }//GEN-LAST:event_userNameFocusGained
    
    private void userNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameActionPerformed

    private void userNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userNameFocusLost
        if(userName.getText().length()==0){
            //add placeholder
            addPlaceholder(userName);
            userName.setText("Username");
        }
    }//GEN-LAST:event_userNameFocusLost
          
    private void jLabel_Register_formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Register_formMouseClicked
        RegistrationFrom rgf = new RegistrationFrom();
        rgf.setVisible(true); //This will open register form page
        this.dispose(); //Set page disappeare
    }//GEN-LAST:event_jLabel_Register_formMouseClicked

    private void jButton_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_loginActionPerformed
    
    //Verify the credentials provided by the users
    checkData();
   
    }//GEN-LAST:event_jButton_loginActionPerformed

    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_login;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_Register_form;
    private javax.swing.JLabel jLabel_passIcon;
    private javax.swing.JLabel jLabel_userIcon;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField password;
    private javax.swing.JComboBox<String> position;
    private javax.swing.JTextField userName;
    // End of variables declaration//GEN-END:variables
}
