package co.system.LoginForm;

import java.awt.Color;
import java.awt.Font;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;


public class RegistrationFrom extends javax.swing.JFrame {

    /**
     * Creates new form RegistrationFrom
     */
    public RegistrationFrom() {
        initComponents();
        //Setting window location to the center
        setLocationRelativeTo(null);
        
        //calling placehlder functions for each field
        addPlaceholder(jTextField_fullName);
        addPlaceholder(jTextField_email);
        addPlaceholder(jTextField_phone_number);
        addPlaceholder(jTextField_userId);
    }

    //Creating placeholder functions setting and removing placeholder   
    
        public void addPlaceholder(JTextField textField){
        Font font = textField.getFont();
        font = font.deriveFont(Font.ITALIC); //setting font
        textField.setFont(font);
        textField.setForeground(Color.gray); //setting color
        
    }
    
       public void removePlaceholder(JTextField textField){
        Font font = textField.getFont();
        font = font.deriveFont(Font.PLAIN);
        textField.setFont(font);
        textField.setForeground(Color.black);
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel_username_icon = new javax.swing.JLabel();
        jTextField_fullName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField_email = new javax.swing.JTextField();
        jTextField_phone_number = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton_registration = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPassword_set = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jRadioButton_Female = new javax.swing.JRadioButton();
        jRadioButton_Maile = new javax.swing.JRadioButton();
        jLabel_login_form = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jRadioButton_DeliveryStaff = new javax.swing.JRadioButton();
        jRadioButton_ManagingStaff = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jTextField_userId = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(69, 93, 122));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(69, 93, 122));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Create Account");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel_username_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/user.png"))); // NOI18N

        jTextField_fullName.setText("Full name");
        jTextField_fullName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_fullNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_fullNameFocusLost(evt);
            }
        });
        jTextField_fullName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_fullNameActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Email Address.png"))); // NOI18N

        jTextField_email.setText("E-mail");
        jTextField_email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_emailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_emailFocusLost(evt);
            }
        });

        jTextField_phone_number.setText("Phone");
        jTextField_phone_number.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_phone_numberFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_phone_numberFocusLost(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/phone.png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/password.png"))); // NOI18N

        jButton_registration.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_registration.setText("Register");
        jButton_registration.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_registration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_registrationActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Have an account?");

        jLabel2.setBackground(new java.awt.Color(69, 93, 122));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Gender");

        buttonGroup2.add(jRadioButton_Female);
        jRadioButton_Female.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jRadioButton_Female.setText("Female");

        buttonGroup2.add(jRadioButton_Maile);
        jRadioButton_Maile.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jRadioButton_Maile.setText("Male");

        jLabel_login_form.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_login_form.setForeground(new java.awt.Color(0, 0, 255));
        jLabel_login_form.setText("Login");
        jLabel_login_form.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_login_form.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_login_formMouseClicked(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(69, 93, 122));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Position");

        buttonGroup1.add(jRadioButton_DeliveryStaff);
        jRadioButton_DeliveryStaff.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jRadioButton_DeliveryStaff.setText("Delivery staff");

        buttonGroup1.add(jRadioButton_ManagingStaff);
        jRadioButton_ManagingStaff.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jRadioButton_ManagingStaff.setText("Managing staff");
        jRadioButton_ManagingStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_ManagingStaffActionPerformed(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(69, 93, 122));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("User ID");

        jTextField_userId.setText("e.g 025(any three digits)");
        jTextField_userId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_userIdFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_userIdFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel_login_form, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton_registration, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel9)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextField_userId, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addGap(18, 18, 18)
                                                .addComponent(jRadioButton_Maile, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jRadioButton_Female, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel8)
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jRadioButton_DeliveryStaff, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jRadioButton_ManagingStaff, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel_username_icon)
                                                    .addComponent(jLabel1)
                                                    .addComponent(jLabel4)
                                                    .addComponent(jLabel5))
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                                        .addGap(28, 28, 28)
                                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jTextField_fullName, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(jTextField_email, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jPassword_set, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(jTextField_phone_number, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(38, 38, 38)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel_username_icon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField_fullName))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField_email))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField_phone_number))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPassword_set))
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextField_userId, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 21, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jRadioButton_ManagingStaff))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton_DeliveryStaff)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jRadioButton_Female)
                    .addComponent(jRadioButton_Maile))
                .addGap(22, 22, 22)
                .addComponent(jButton_registration, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_login_form))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_fullNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_fullNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_fullNameActionPerformed

    private void jTextField_fullNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_fullNameFocusGained
        if(jTextField_fullName.getText().equals("Full name")){
            jTextField_fullName.setText(null);
            jTextField_fullName.requestFocus();
            //remove Placeholder
            removePlaceholder(jTextField_fullName);
        }    
    }//GEN-LAST:event_jTextField_fullNameFocusGained

    private void jTextField_emailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_emailFocusGained
           if(jTextField_email.getText().equals("E-mail")){
            jTextField_email.setText(null);
            jTextField_email.requestFocus();
            //remove Placeholder
            removePlaceholder(jTextField_email);
        } 
    }//GEN-LAST:event_jTextField_emailFocusGained

    private void jTextField_phone_numberFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_phone_numberFocusGained
              if(jTextField_phone_number.getText().equals("Phone")){
            jTextField_phone_number.setText(null);
            jTextField_phone_number.requestFocus();
            //remove Placeholder
            removePlaceholder(jTextField_phone_number);
        }
    }//GEN-LAST:event_jTextField_phone_numberFocusGained

    private void jTextField_fullNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_fullNameFocusLost
        if(jTextField_fullName.getText().length()==0){
            //add placeholder
            addPlaceholder(jTextField_fullName);
            jTextField_fullName.setText("Full name");
    }//GEN-LAST:event_jTextField_fullNameFocusLost
    }
    private void jTextField_emailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_emailFocusLost
        if(jTextField_email.getText().length()==0){
            //add placeholder
            addPlaceholder(jTextField_email);
            jTextField_email.setText("E-mail");
    }//GEN-LAST:event_jTextField_emailFocusLost
    }
    
    private void jLabel_login_formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_login_formMouseClicked
        LoginForm lf = new LoginForm();
        lf.setVisible(true); //This will make Login page appeare
        this.dispose(); //this will disappeare registration form
    }//GEN-LAST:event_jLabel_login_formMouseClicked

    private void jButton_registrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_registrationActionPerformed
        
        //Writing into Registration file
        
        String userPosition = "";
        if(jRadioButton_DeliveryStaff.isSelected()==true){
            userPosition="Delivery staff";
        }else if(jRadioButton_ManagingStaff.isSelected()==true){
            userPosition="Managing staff";
        }
        
        String userGender = "";
        if(jRadioButton_Maile.isSelected()==true){
            userGender="male";
        }else if(jRadioButton_Female.isSelected()==true){
            userGender="female";
        }
        
//        UserCurd user = new UserCurd();
//        try {
//            if(jTextField_userId.getText().equals("")||
//                    jTextField_fullName.getText().equals("")||
//                    jPassword_set.getText().equals("")||
//                    userPosition.equals("")||userGender.equals("")||
//                    jTextField_email.getText().equals("")||
//                    jTextField_phone_number.getText().equals(""))
//            {
//                JOptionPane.showMessageDialog(null, "Fill all the fields completely.");
//                
//            }else{
//            user.addUsers(jTextField_userId.getText()
//                    ,jTextField_fullName.getText()
//                    ,jPassword_set.getText()
//                    ,userPosition
//                    , userGender
//                    ,jTextField_email.getText()
//                    ,jTextField_phone_number.getText());
//            JOptionPane.showMessageDialog(null, "Register successful.");
//        }
//        } catch (Exception ex) {
//            Logger.getLogger(RegistrationFrom.class.getName()).log(Level.SEVERE, null, ex);
//        }
//        
//        
    }//GEN-LAST:event_jButton_registrationActionPerformed

    private void jRadioButton_ManagingStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_ManagingStaffActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton_ManagingStaffActionPerformed

    private void jTextField_userIdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_userIdFocusGained
                      if(jTextField_userId.getText().equals("e.g 025(any three digits)")){
            jTextField_userId.setText(null);
            jTextField_userId.requestFocus();
            //remove Placeholder
            removePlaceholder(jTextField_userId);
        }
    }//GEN-LAST:event_jTextField_userIdFocusGained
    
    private void jTextField_phone_numberFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_phone_numberFocusLost
                if(jTextField_phone_number.getText().length()==0){
            //add placeholder
            addPlaceholder(jTextField_phone_number);
            jTextField_phone_number.setText("Phone");
        }
    }//GEN-LAST:event_jTextField_phone_numberFocusLost

    private void jTextField_userIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_userIdFocusLost
                if(jTextField_userId.getText().length()==0){
            //add placeholder
            addPlaceholder(jTextField_userId);
            jTextField_userId.setText("e.g 025(any three digits)");
        }        
    }//GEN-LAST:event_jTextField_userIdFocusLost
    
    

    
    
    public static void main(String args[]){

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrationFrom().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton_registration;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_login_form;
    private javax.swing.JLabel jLabel_username_icon;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPassword_set;
    private javax.swing.JRadioButton jRadioButton_DeliveryStaff;
    private javax.swing.JRadioButton jRadioButton_Female;
    private javax.swing.JRadioButton jRadioButton_Maile;
    private javax.swing.JRadioButton jRadioButton_ManagingStaff;
    private javax.swing.JTextField jTextField_email;
    private javax.swing.JTextField jTextField_fullName;
    private javax.swing.JTextField jTextField_phone_number;
    private javax.swing.JTextField jTextField_userId;
    // End of variables declaration//GEN-END:variables
}
