
package co.system.userManagementForm;

import co.system.Dao.UserAndProductDao;
import co.system.Dao.UserAndProductDaoImpl;
import co.system.LoginForm.LoginForm;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

public class Reports extends javax.swing.JFrame {

    public Reports() {
        initComponents();
        setLocationRelativeTo(null);
        setCurrentDate(report_date);
        viewUserData();
        viewDeliveryData();
        viewPendingData();
        setNumbers();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton_return_Dashboard = new javax.swing.JButton();
        report_date = new javax.swing.JLabel();
        Admin_name = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel_orangeBar = new javax.swing.JPanel();
        jLabel = new javax.swing.JLabel();
        userReportInfo = new javax.swing.JLabel();
        jPanel_greenBar = new javax.swing.JPanel();
        deliveryReportInfo = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel_redBar = new javax.swing.JPanel();
        jLabel_salesProduct = new javax.swing.JLabel();
        pendingReportInfo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        userReport = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        pendingReport = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        deliveryReport = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(162, 219, 250));

        jPanel2.setBackground(new java.awt.Color(57, 162, 219));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Report");

        jButton_return_Dashboard.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_return_Dashboard.setText("Dashboard");
        jButton_return_Dashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_return_Dashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_return_DashboardActionPerformed(evt);
            }
        });

        report_date.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        report_date.setText("Date");

        Admin_name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Admin_name.setText("Admin");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Welcom");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Admin_name, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(report_date, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(105, 105, 105)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 294, Short.MAX_VALUE)
                .addComponent(jButton_return_Dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(report_date)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Admin_name)
                                    .addComponent(jLabel8)))
                            .addComponent(jLabel1)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jButton_return_Dashboard)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel_orangeBar.setBackground(new java.awt.Color(255, 153, 0));

        jLabel.setBackground(new java.awt.Color(255, 102, 51));
        jLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel.setText("Users");
        jLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel.setOpaque(true);

        userReportInfo.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        userReportInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userReportInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/UsersInfo.png"))); // NOI18N
        userReportInfo.setText("0");
        userReportInfo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        userReportInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userReportInfoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel_orangeBarLayout = new javax.swing.GroupLayout(jPanel_orangeBar);
        jPanel_orangeBar.setLayout(jPanel_orangeBarLayout);
        jPanel_orangeBarLayout.setHorizontalGroup(
            jPanel_orangeBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_orangeBarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(userReportInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel_orangeBarLayout.setVerticalGroup(
            jPanel_orangeBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_orangeBarLayout.createSequentialGroup()
                .addComponent(jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userReportInfo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel_greenBar.setBackground(new java.awt.Color(102, 255, 102));

        deliveryReportInfo.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        deliveryReportInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        deliveryReportInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/delivery (1).png"))); // NOI18N
        deliveryReportInfo.setText("0");
        deliveryReportInfo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deliveryReportInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deliveryReportInfoMouseClicked(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(0, 204, 0));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Delivery");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel5.setOpaque(true);

        javax.swing.GroupLayout jPanel_greenBarLayout = new javax.swing.GroupLayout(jPanel_greenBar);
        jPanel_greenBar.setLayout(jPanel_greenBarLayout);
        jPanel_greenBarLayout.setHorizontalGroup(
            jPanel_greenBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(deliveryReportInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
        );
        jPanel_greenBarLayout.setVerticalGroup(
            jPanel_greenBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_greenBarLayout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deliveryReportInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel_redBar.setBackground(new java.awt.Color(255, 102, 102));

        jLabel_salesProduct.setBackground(new java.awt.Color(204, 0, 51));
        jLabel_salesProduct.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_salesProduct.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_salesProduct.setText("Pending");
        jLabel_salesProduct.setOpaque(true);

        pendingReportInfo.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        pendingReportInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pendingReportInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/pending.png"))); // NOI18N
        pendingReportInfo.setText("0");
        pendingReportInfo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pendingReportInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pendingReportInfoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel_redBarLayout = new javax.swing.GroupLayout(jPanel_redBar);
        jPanel_redBar.setLayout(jPanel_redBarLayout);
        jPanel_redBarLayout.setHorizontalGroup(
            jPanel_redBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_salesProduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pendingReportInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
        );
        jPanel_redBarLayout.setVerticalGroup(
            jPanel_redBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_redBarLayout.createSequentialGroup()
                .addComponent(jLabel_salesProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pendingReportInfo)
                .addGap(48, 48, 48))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("User Information");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Pending Information");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Delivery Information");

        userReport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Full Name", "E-mail", "Phone", "Password", "Position", "Gender"
            }
        ));
        jScrollPane1.setViewportView(userReport);

        pendingReport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tracking code", "Receiver", "Sender", "Send From", "Destination", "Date", "Weight/Item"
            }
        ));
        jScrollPane2.setViewportView(pendingReport);

        deliveryReport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tracking code", "Receiver", "Sender", "Send From", "Destination", "Date", "Weight/Item"
            }
        ));
        jScrollPane3.setViewportView(deliveryReport);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addComponent(jPanel_orangeBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119)
                .addComponent(jPanel_greenBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(122, 122, 122)
                .addComponent(jPanel_redBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel_redBar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel_orangeBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addComponent(jLabel2))
                    .addComponent(jPanel_greenBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    LocalDate currentDate = LocalDate.now();
    UserDashboard dashboard = new UserDashboard();
    
    private void userReportInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userReportInfoMouseClicked

    }//GEN-LAST:event_userReportInfoMouseClicked

    private void deliveryReportInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deliveryReportInfoMouseClicked

    }//GEN-LAST:event_deliveryReportInfoMouseClicked

    private void pendingReportInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pendingReportInfoMouseClicked

    }//GEN-LAST:event_pendingReportInfoMouseClicked
    
    private void jButton_return_DashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_return_DashboardActionPerformed
        
        dashboard.setVisible(true);
        dashboard.setDashName(Admin_name.getText());
        this.dispose();
        if(Admin_name.getText().equalsIgnoreCase("suman dangol")){
           dashboard.setUserImage(Admin_name.getText()); 
        }else{
            dashboard.setUserImage("userImage");
//            getGender(Admin_user_name_report.getText());
        }
    }//GEN-LAST:event_jButton_return_DashboardActionPerformed

private void viewUserData() {
    	
    	ArrayList dataList;
    	UserAndProductDao user = new UserAndProductDaoImpl();
    	
    	try {
                dataList = user.viewUser();
                DefaultTableModel dtm = (DefaultTableModel) userReport.getModel();
                Object[] lines = dataList.toArray();
                for( int i = 0 ; i<lines.length;i++) {
                    String line = lines[i].toString();
                    String [] row = line.split(",");
                    dtm.addRow(row);
            }


            } catch (IOException e) {
                Logger.getLogger(UserDashboard.class.getName()).log(Level.SEVERE, null, e);
            }	
    }
    
 private void viewPendingData() {
    	
    ArrayList dataList;
    UserAndProductDao user = new UserAndProductDaoImpl();

    try {
            dataList = user.viewPending();
            DefaultTableModel dtm = (DefaultTableModel) pendingReport.getModel();
            Object[] lines = dataList.toArray();
            for( int i = 0 ; i<lines.length;i++) {
                    String line = lines[i].toString();
                    String [] row = line.split(",");
                    dtm.addRow(row);
        }


        } catch (IOException e) {

                Logger.getLogger(Reports.class.getName()).log(Level.SEVERE, null, e);
        }
	
    }
 
 private void viewDeliveryData() {
 	
    ArrayList dataList;
    UserAndProductDao user = new UserAndProductDaoImpl();

    try {
            dataList = user.viewDelivery();
            DefaultTableModel dtm = (DefaultTableModel) deliveryReport.getModel();
            Object[] lines = dataList.toArray();
            for( int i = 0 ; i<lines.length;i++) {
                    String line = lines[i].toString();
                    String [] row = line.split(",");
                    dtm.addRow(row);
            }


        } catch (IOException e) {

                Logger.getLogger(Reports.class.getName()).log(Level.SEVERE, null, e);
        }	
 }
    
    
    private int number(String fileName){
        //Create a new file and provide path(location) of a file
        String path="src\\File_collection\\";
        String readLines="";
        int totalCounts=0;
        File file = new File(path+fileName);
        try {
            //Since it is in read mode, data is reading from the file 
            BufferedReader br = new BufferedReader(new FileReader(file));
            while((readLines=br.readLine()) != null){
                totalCounts++;
            }
  
        } catch (FileNotFoundException ex) {
            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE,null,ex);
        } catch (IOException ex) {
            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE,null,ex);
        }

        return totalCounts;
    }
    
    private void setNumbers(){ 
        
        userReportInfo.setText(String.valueOf(number("userInformation.txt")));
        pendingReportInfo.setText(String.valueOf(number("pendingInfo.txt")));
        deliveryReportInfo.setText(String.valueOf(number("deliveryInfo.txt")));
    }
    
    public void setUserName(String name){
        Admin_name.setText(name);
    }
    
        public void setCurrentDate(JLabel jlabel){
        SimpleDateFormat sdfDate = new SimpleDateFormat("E, MMM dd yyyy | hh:mm:ss aa");
        Timer time = new Timer(500, new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
                jlabel.setText(sdfDate.format(new Date(System.currentTimeMillis())));
            }
        });
        time.setRepeats(true);
        time.start(); 
    }   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reports().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Admin_name;
    private javax.swing.JTable deliveryReport;
    private javax.swing.JLabel deliveryReportInfo;
    private javax.swing.JButton jButton_return_Dashboard;
    private javax.swing.JLabel jLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel_salesProduct;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel_greenBar;
    private javax.swing.JPanel jPanel_orangeBar;
    private javax.swing.JPanel jPanel_redBar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable pendingReport;
    private javax.swing.JLabel pendingReportInfo;
    private javax.swing.JLabel report_date;
    private javax.swing.JTable userReport;
    private javax.swing.JLabel userReportInfo;
    // End of variables declaration//GEN-END:variables
}
