
package co.system.userManagementForm;
 

import co.system.Dao.UserAndProductDao;
import co.system.Dao.UserAndProductDaoImpl;
import co.system.LoginForm.LoginForm;
import co.system.bll.UserAndProduct;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Date;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

public class UserDashboard extends javax.swing.JFrame {

    public UserDashboard() {
        initComponents();
        setLocationRelativeTo(null);
        setCurrentDate(dash_date);
        setCurrentDate(user_date);
        setCurrentDate(pending_date);
        setCurrentDate(delivery_date);
        setNumbers();
        viewUserData();
        viewDeliveryData();
        viewPendingData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        User_Image = new javax.swing.JLabel();
        admin_name = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Dashboard = new javax.swing.JLabel();
        Dash_User = new javax.swing.JLabel();
        Dash_Pending = new javax.swing.JLabel();
        Dash_Delivery = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Dash_Report = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        dashboardPanel = new javax.swing.JPanel();
        jPanel_orangeBar = new javax.swing.JPanel();
        jLabel = new javax.swing.JLabel();
        userInfo = new javax.swing.JLabel();
        jPanel_greenBar = new javax.swing.JPanel();
        deliveryInfo = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel_redBar = new javax.swing.JPanel();
        jLabel_salesProduct = new javax.swing.JLabel();
        pendingInfo = new javax.swing.JLabel();
        jPanel_redBar1 = new javax.swing.JPanel();
        jLabel_salesProduct1 = new javax.swing.JLabel();
        reportInfo = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        dash_date = new javax.swing.JLabel();
        userPanel = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        user_date = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        user_id = new javax.swing.JTextField();
        user_password = new javax.swing.JTextField();
        user_phone = new javax.swing.JTextField();
        user_email = new javax.swing.JTextField();
        user_name = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jComboBox_position = new javax.swing.JComboBox<>();
        jRadioButton_male = new javax.swing.JRadioButton();
        jRadioButton_female = new javax.swing.JRadioButton();
        User_Add = new javax.swing.JButton();
        User_Update = new javax.swing.JButton();
        User_Delete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        userInformation = new javax.swing.JTable();
        pendingPanel = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        pending_date = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        PendingInformation = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        pendi_weight_item = new javax.swing.JTextField();
        pend_code = new javax.swing.JTextField();
        pend_receiver = new javax.swing.JTextField();
        pendi_sender = new javax.swing.JTextField();
        pend_send_from = new javax.swing.JTextField();
        pend_destination = new javax.swing.JTextField();
        Pend_Update = new javax.swing.JButton();
        Pend_Delete = new javax.swing.JButton();
        Pend_Add = new javax.swing.JButton();
        deliveryPending = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        delivery_date = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        deliveryInformation = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 153, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        User_Image.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(User_Image, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 200, 150));

        admin_name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        admin_name.setText("Admin");
        jPanel2.add(admin_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 130, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Welcome");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 60, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 200));

        Dashboard.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Dashboard.setText("Dashboard");
        Dashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DashboardMouseClicked(evt);
            }
        });
        jPanel1.add(Dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 272, 137, -1));

        Dash_User.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Dash_User.setText("User");
        Dash_User.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Dash_User.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Dash_UserMouseClicked(evt);
            }
        });
        jPanel1.add(Dash_User, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 319, 137, -1));

        Dash_Pending.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Dash_Pending.setText("Pending");
        Dash_Pending.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Dash_Pending.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Dash_PendingMouseClicked(evt);
            }
        });
        jPanel1.add(Dash_Pending, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 366, 137, -1));

        Dash_Delivery.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Dash_Delivery.setText("Delivery");
        Dash_Delivery.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Dash_Delivery.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Dash_DeliveryMouseClicked(evt);
            }
        });
        jPanel1.add(Dash_Delivery, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 413, 137, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Logout");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 600, 110, 30));

        Dash_Report.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Dash_Report.setText("Report");
        Dash_Report.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Dash_Report.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Dash_ReportMouseClicked(evt);
            }
        });
        jPanel1.add(Dash_Report, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 460, 137, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 710));

        jTabbedPane1.setBackground(new java.awt.Color(255, 102, 102));

        dashboardPanel.setBackground(new java.awt.Color(204, 204, 204));
        dashboardPanel.setMinimumSize(new java.awt.Dimension(899, 710));
        dashboardPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel_orangeBar.setBackground(new java.awt.Color(255, 153, 0));

        jLabel.setBackground(new java.awt.Color(255, 102, 51));
        jLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel.setText("Users");
        jLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel.setOpaque(true);

        userInfo.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        userInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/UsersInfo.png"))); // NOI18N
        userInfo.setText("0");
        userInfo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        userInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userInfoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel_orangeBarLayout = new javax.swing.GroupLayout(jPanel_orangeBar);
        jPanel_orangeBar.setLayout(jPanel_orangeBarLayout);
        jPanel_orangeBarLayout.setHorizontalGroup(
            jPanel_orangeBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel_orangeBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(userInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel_orangeBarLayout.setVerticalGroup(
            jPanel_orangeBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_orangeBarLayout.createSequentialGroup()
                .addComponent(jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        dashboardPanel.add(jPanel_orangeBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, -1, 160));

        jPanel_greenBar.setBackground(new java.awt.Color(102, 255, 102));

        deliveryInfo.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        deliveryInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        deliveryInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/delivery (1).png"))); // NOI18N
        deliveryInfo.setText("0");
        deliveryInfo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deliveryInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deliveryInfoMouseClicked(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(0, 204, 0));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Delivery");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel5.setOpaque(true);

        javax.swing.GroupLayout jPanel_greenBarLayout = new javax.swing.GroupLayout(jPanel_greenBar);
        jPanel_greenBar.setLayout(jPanel_greenBarLayout);
        jPanel_greenBarLayout.setHorizontalGroup(
            jPanel_greenBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel_greenBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(deliveryInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel_greenBarLayout.setVerticalGroup(
            jPanel_greenBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_greenBarLayout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deliveryInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                .addContainerGap())
        );

        dashboardPanel.add(jPanel_greenBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 460, -1, 160));

        jPanel_redBar.setBackground(new java.awt.Color(255, 102, 102));

        jLabel_salesProduct.setBackground(new java.awt.Color(204, 0, 51));
        jLabel_salesProduct.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_salesProduct.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_salesProduct.setText("Pending");
        jLabel_salesProduct.setOpaque(true);

        pendingInfo.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        pendingInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pendingInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/pending.png"))); // NOI18N
        pendingInfo.setText("0");
        pendingInfo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pendingInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pendingInfoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel_redBarLayout = new javax.swing.GroupLayout(jPanel_redBar);
        jPanel_redBar.setLayout(jPanel_redBarLayout);
        jPanel_redBarLayout.setHorizontalGroup(
            jPanel_redBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_salesProduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_redBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pendingInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel_redBarLayout.setVerticalGroup(
            jPanel_redBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_redBarLayout.createSequentialGroup()
                .addComponent(jLabel_salesProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pendingInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        dashboardPanel.add(jPanel_redBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 250, -1, 160));

        jPanel_redBar1.setBackground(new java.awt.Color(162, 219, 250));

        jLabel_salesProduct1.setBackground(new java.awt.Color(57, 162, 219));
        jLabel_salesProduct1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_salesProduct1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_salesProduct1.setText("Report");
        jLabel_salesProduct1.setOpaque(true);

        reportInfo.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        reportInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        reportInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/report.png"))); // NOI18N
        reportInfo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reportInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reportInfoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel_redBar1Layout = new javax.swing.GroupLayout(jPanel_redBar1);
        jPanel_redBar1.setLayout(jPanel_redBar1Layout);
        jPanel_redBar1Layout.setHorizontalGroup(
            jPanel_redBar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_salesProduct1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel_redBar1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(reportInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel_redBar1Layout.setVerticalGroup(
            jPanel_redBar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_redBar1Layout.createSequentialGroup()
                .addComponent(jLabel_salesProduct1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(reportInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                .addContainerGap())
        );

        dashboardPanel.add(jPanel_redBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 460, -1, -1));

        jPanel3.setBackground(new java.awt.Color(0, 153, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Dashboard");

        dash_date.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        dash_date.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dash_date.setText("Date");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(341, 341, 341)
                        .addComponent(jLabel1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(302, 302, 302)
                        .addComponent(dash_date, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(317, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(dash_date)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        dashboardPanel.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 899, -1));

        jTabbedPane1.addTab("tab1", dashboardPanel);

        userPanel.setBackground(new java.awt.Color(255, 153, 0));
        userPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 102, 51));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setText("User Information");

        user_date.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        user_date.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        user_date.setText("Date");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(295, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(290, 290, 290))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(user_date, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(305, 305, 305))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(user_date)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        userPanel.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 899, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("ID");
        userPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 239, 119, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Phone");
        userPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 356, 119, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Full Name");
        userPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 277, 119, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("E-mail");
        userPanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 316, 119, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Password");
        userPanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(554, 239, 119, -1));

        user_id.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        userPanel.add(user_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 239, 150, -1));

        user_password.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        userPanel.add(user_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(677, 239, 150, -1));

        user_phone.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        userPanel.add(user_phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 356, 150, -1));

        user_email.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        userPanel.add(user_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 316, 150, -1));

        user_name.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        userPanel.add(user_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 277, 150, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Position");
        userPanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(554, 277, 119, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Gender");
        userPanel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(554, 316, 119, -1));

        jComboBox_position.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBox_position.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select", "Managing staff", "Delivery staff" }));
        userPanel.add(jComboBox_position, new org.netbeans.lib.awtextra.AbsoluteConstraints(677, 277, 150, -1));

        buttonGroup1.add(jRadioButton_male);
        jRadioButton_male.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jRadioButton_male.setText("Male");
        userPanel.add(jRadioButton_male, new org.netbeans.lib.awtextra.AbsoluteConstraints(679, 315, 56, -1));

        buttonGroup1.add(jRadioButton_female);
        jRadioButton_female.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jRadioButton_female.setText("Female");
        userPanel.add(jRadioButton_female, new org.netbeans.lib.awtextra.AbsoluteConstraints(768, 315, -1, -1));

        User_Add.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        User_Add.setText("Add");
        User_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                User_AddActionPerformed(evt);
            }
        });
        userPanel.add(User_Add, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 394, 73, -1));

        User_Update.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        User_Update.setText("Update");
        User_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                User_UpdateActionPerformed(evt);
            }
        });
        userPanel.add(User_Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 394, -1, -1));

        User_Delete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        User_Delete.setText("Delete");
        User_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                User_DeleteActionPerformed(evt);
            }
        });
        userPanel.add(User_Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(754, 394, 73, -1));

        userInformation.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Full name", "E-mail", "Phone", "Password", "Position", "Gender"
            }
        ));
        userInformation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userInformationMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(userInformation);

        userPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 860, 230));

        jTabbedPane1.addTab("tab2", userPanel);

        pendingPanel.setBackground(new java.awt.Color(255, 102, 102));
        pendingPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(204, 0, 51));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel15.setText("Pending Information");

        pending_date.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pending_date.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pending_date.setText("Date");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(272, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(249, 249, 249))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(pending_date, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(300, 300, 300))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addComponent(pending_date)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pendingPanel.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, -1));

        PendingInformation.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tracking code", "Receiver", "Sender", "Send From", "Destination", "Date", "Weight/Item"
            }
        ));
        PendingInformation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PendingInformationMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(PendingInformation);

        pendingPanel.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 863, 250));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("Weight/Item");
        pendingPanel.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 250, 100, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("Tracking code");
        pendingPanel.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 100, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText("Receiver");
        pendingPanel.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 100, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setText("Sender");
        pendingPanel.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 100, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setText("Send From");
        pendingPanel.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 100, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setText("Destination");
        pendingPanel.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 220, 100, -1));

        pendi_weight_item.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        pendingPanel.add(pendi_weight_item, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 250, 170, -1));

        pend_code.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        pendingPanel.add(pend_code, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 170, -1));

        pend_receiver.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        pendingPanel.add(pend_receiver, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 170, -1));

        pendi_sender.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        pendingPanel.add(pendi_sender, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 170, -1));

        pend_send_from.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        pendingPanel.add(pend_send_from, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 170, -1));

        pend_destination.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        pendingPanel.add(pend_destination, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 220, 170, -1));

        Pend_Update.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Pend_Update.setText("Update");
        Pend_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pend_UpdateActionPerformed(evt);
            }
        });
        pendingPanel.add(Pend_Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 370, -1, -1));

        Pend_Delete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Pend_Delete.setText("Delete");
        Pend_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pend_DeleteActionPerformed(evt);
            }
        });
        pendingPanel.add(Pend_Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 370, -1, -1));

        Pend_Add.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Pend_Add.setText("Add");
        Pend_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pend_AddActionPerformed(evt);
            }
        });
        pendingPanel.add(Pend_Add, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, -1, -1));

        jTabbedPane1.addTab("tab3", pendingPanel);

        deliveryPending.setBackground(new java.awt.Color(102, 255, 102));
        deliveryPending.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(0, 204, 0));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel13.setText("Delivery Information");

        delivery_date.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        delivery_date.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        delivery_date.setText("Date");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(251, 251, 251)
                        .addComponent(jLabel13))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(307, 307, 307)
                        .addComponent(delivery_date, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(266, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(delivery_date)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        deliveryPending.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 899, -1));

        deliveryInformation.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tracking code", "Receiver", "Sender", "Send From", "Destination", "Date", "Weight/Item"
            }
        ));
        jScrollPane2.setViewportView(deliveryInformation);

        deliveryPending.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 221, 860, 430));

        jTabbedPane1.addTab("tab4", deliveryPending);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, -28, -1, 990));

        pack();
    }// </editor-fold>//GEN-END:initComponents

//    Counting c = new Counting();
//    UserCurd users = new UserCurd();
//    ProductCurd pc = new ProductCurd();
    LocalDate currentDate = LocalDate.now();
    
    private void reportInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportInfoMouseClicked
        Reports report = new Reports();
        report.setVisible(true);
        report.setUserName(admin_name.getText());
        this.dispose();
    }//GEN-LAST:event_reportInfoMouseClicked

    private void pendingInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pendingInfoMouseClicked
        jTabbedPane1.setSelectedIndex(2);
        clearFieldPending();
        clearFieldUser();
    }//GEN-LAST:event_pendingInfoMouseClicked

    private void deliveryInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deliveryInfoMouseClicked
        jTabbedPane1.setSelectedIndex(3);
        clearFieldPending();
        clearFieldUser();
    }//GEN-LAST:event_deliveryInfoMouseClicked

    private void userInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userInfoMouseClicked
        jTabbedPane1.setSelectedIndex(1);
        clearFieldPending();
        clearFieldUser();
    }//GEN-LAST:event_userInfoMouseClicked

    private void DashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DashboardMouseClicked
        jTabbedPane1.setSelectedIndex(0);
        clearFieldPending();
        clearFieldUser();
        setNumbers();
    }//GEN-LAST:event_DashboardMouseClicked

    private void Dash_UserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Dash_UserMouseClicked
        jTabbedPane1.setSelectedIndex(1);
        clearFieldPending();
        clearFieldUser();
    }//GEN-LAST:event_Dash_UserMouseClicked

    private void Dash_PendingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Dash_PendingMouseClicked
        jTabbedPane1.setSelectedIndex(2);
        clearFieldPending();
        clearFieldUser();
    }//GEN-LAST:event_Dash_PendingMouseClicked

    private void Dash_DeliveryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Dash_DeliveryMouseClicked
        jTabbedPane1.setSelectedIndex(3);
        clearFieldPending();
        clearFieldUser();
    }//GEN-LAST:event_Dash_DeliveryMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        LoginForm login = new LoginForm();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Dash_ReportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Dash_ReportMouseClicked
        Reports report = new Reports();
        report.setVisible(true);
        report.setUserName(admin_name.getText());
        this.dispose();
    }//GEN-LAST:event_Dash_ReportMouseClicked

    private void User_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_User_AddActionPerformed
        
        //Add user data 
        
        
    	UserAndProductDao userss = new UserAndProductDaoImpl();
        UserAndProduct user = new UserAndProduct();
        
        String position="";
        position= jComboBox_position.getSelectedItem().toString() ;
        
        String genders="";
        if(jRadioButton_male.isSelected()==true){
	        genders="Male";
	    }else{
	        genders="Female";
	    }


        
        if(user_id.getText().equals("")||
                user_name.getText().equals("")||
                user_password.getText().equals("")||
                position.equals("")||
                genders.equals("")|| 
                user_email.getText().equals("")|| 
                user_phone.getText().equals("")){
            
            JOptionPane.showMessageDialog(null, "Please fill all the fields Properly !","Error",JOptionPane.ERROR_MESSAGE);
        }else{
             try {
            	 
            	 int sid =Integer.parseInt(user_id.getText());
            	 user.setUserId(sid);
            	 user.setUserName(user_name.getText());
            	 user.setEmail(user_email.getText());
            	 user.setGender(genders);
            	 user.setPassword(user_password.getText());
            	 user.setPosition(position);
            	 user.setPhone(user_phone.getText());
            	 
            	 userss.addUser(user);
                 
            } catch (Exception ex) {
                Logger.getLogger(UserDashboard.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        clearData(userInformation);
        viewUserData();
        clearFieldUser();
        
    }//GEN-LAST:event_User_AddActionPerformed

    private void User_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_User_UpdateActionPerformed
        
        //Update the selected user row's data
        
        UserAndProductDao userss = new UserAndProductDaoImpl();
        UserAndProduct user = new UserAndProduct();
        
        String position="";
        position= jComboBox_position.getSelectedItem().toString() ;
        
        String genders="";
        if(jRadioButton_male.isSelected()==true){
	        genders="Male";
	    }else{
	        genders="Female";
	    }
        
        if(user_id.getText().equals("")|| 
                user_name.getText().equals("")||
                user_password.getText().equals("")||
                position.equals("")||
                genders.equals("")|| 
                user_email.getText().equals("")|| 
                user_phone.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this, "Please select a row to update!","Error",JOptionPane.ERROR_MESSAGE);
        }else{
                    try {
                    	
                    int sid =Integer.parseInt(user_id.getText());
                   	 user.setUserId(sid);
                   	 user.setUserName(user_name.getText());
                   	 user.setEmail(user_email.getText());
                   	 user.setGender(genders);
                   	 user.setPassword(user_password.getText());
                   	 user.setPosition(position);
                   	 user.setPhone(user_phone.getText());
                   	 
                   	userss.updateUser(user);
                        
        } catch (IOException ex) {
            Logger.getLogger(UserDashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        clearData(userInformation);
        viewUserData();
        clearFieldUser();
    }//GEN-LAST:event_User_UpdateActionPerformed

    private void User_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_User_DeleteActionPerformed
        
        //Delete the selected user row's data
        
        UserAndProductDao userss = new UserAndProductDaoImpl();
        UserAndProduct user = new UserAndProduct();
        
        String position="";
        position= jComboBox_position.getSelectedItem().toString() ;
        
        String genders="";
        if(jRadioButton_male.isSelected()==true){
	        genders="Male";
	    }else{
	        genders="Female";
	    }
    	
        if(user_id.getText().equals("")|| 
                user_name.getText().equals("")||
                user_password.getText().equals("")||
                position.equals("")||
                genders.equals("")|| 
                user_email.getText().equals("")|| 
                user_phone.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this, "Please select a row to delete!","Error",JOptionPane.ERROR_MESSAGE);
        }
        try {
            int ids = Integer.parseInt(user_id.getText());
        	user.setUserId(ids);
        	userss.deleteUser(user);

        } catch (IOException ex) {
            Logger.getLogger(UserDashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
        clearData(userInformation);
        viewUserData();
        clearFieldUser();
        
    }//GEN-LAST:event_User_DeleteActionPerformed

    private void Pend_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pend_AddActionPerformed

        //Add pending data
        
        UserAndProductDao userss = new UserAndProductDaoImpl();
        UserAndProduct user = new UserAndProduct();
        
        if(pend_code.getText().equals("")|| 
           pendi_sender.equals("") ||
           pend_receiver.getText().equals("")||
           pend_send_from.getText().equals("")||
           pend_destination.getText().equals("")||
           pendi_weight_item.getText().equals("")
           ){

            JOptionPane.showMessageDialog(this, "Please fill all the fields Properly !","Error",JOptionPane.ERROR_MESSAGE);
        }
        else{
          try {

              int ids = Integer.parseInt(pend_code.getText());
              user.setTracking_code(ids);
              user.setSender(pendi_sender.getText());
              user.setReceiver(pend_receiver.getText());
              user.setSend_from(pend_send_from.getText());
              user.setDestination(pend_destination.getText());
              user.setDate(currentDate.toString());
              user.setWeight_item(pendi_weight_item.getText());

              userss.addProduct(user, "pendingInfo.txt");


          } catch (IOException ex) {
              Logger.getLogger(UserDashboard.class.getName()).log(Level.SEVERE, null, ex);
          }  
        }

        clearData(PendingInformation);
        viewPendingData();
        clearFieldPending();
  
    }//GEN-LAST:event_Pend_AddActionPerformed

    private void Pend_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pend_UpdateActionPerformed
        
        //Updating the selected pending row's data
        
        UserAndProductDao userss = new UserAndProductDaoImpl();
        UserAndProduct user = new UserAndProduct();
        
        String date="";
        File file = new File("src\\File_collection\\pendingInfo.txt");
        
        //Retriving previous date
        try {
            BufferedReader br = new BufferedReader(new FileReader(file));
            String productRecord;
            while((productRecord=br.readLine()) != null){
                if(productRecord.contains(pend_code.getText())){
                    StringTokenizer st = new StringTokenizer(productRecord,",");
                    String code_=st.nextToken();
                    String receiver_ = st.nextToken();
                    String sender_ = st.nextToken();
                    String send_form_ = st.nextToken();
                    String destination_ = st.nextToken();
                    date = st.nextToken();
                    String weight_item_ = st.nextToken();
                    
                }
            }
            br.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(UserDashboard.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(UserDashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        //Adding new data
        if(pend_code.getText().equals("")|| 
             pendi_sender.equals("") ||
             pend_receiver.getText().equals("")||
             pend_send_from.getText().equals("")||
             pend_destination.getText().equals("")||
             pendi_weight_item.getText().equals("")
             ){
              
              JOptionPane.showMessageDialog(this, "Please select a row to update !","Error",JOptionPane.ERROR_MESSAGE);
          }else{
            try {
                
                int ids = Integer.parseInt(pend_code.getText());
            	user.setTracking_code(ids);
            	user.setSender(pendi_sender.getText());
            	user.setReceiver(pend_receiver.getText());
            	user.setSend_from(pend_send_from.getText());
            	user.setDestination(pend_destination.getText());
            	user.setDate(date);
            	user.setWeight_item(pendi_weight_item.getText());
            	
            	userss.addProduct(user, "pendingInfo.txt");
                
            } catch (IOException ex) {
                Logger.getLogger(UserDashboard.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        clearData(PendingInformation);
        viewPendingData();
        clearFieldPending();
    }//GEN-LAST:event_Pend_UpdateActionPerformed

    private void Pend_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pend_DeleteActionPerformed
        
        //Delete the selected pending row's data
        UserAndProductDao userss = new UserAndProductDaoImpl();
        UserAndProduct user = new UserAndProduct();
        
        if(pend_code.getText().equals("")|| 
             pendi_sender.equals("") ||
             pend_receiver.getText().equals("")||
             pend_send_from.getText().equals("")||
             pend_destination.getText().equals("")||
             pendi_weight_item.getText().equals("")
             ){
              
              JOptionPane.showMessageDialog(this, "Please select a row to delete !","Error",JOptionPane.ERROR_MESSAGE);
          }else{
                try {
                    int ids = Integer.parseInt(pend_code.getText());
                	user.setTracking_code(ids);
                	userss.deleteProduct(user);

        } catch (IOException ex) {
            Logger.getLogger(UserDashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        
        clearData(PendingInformation);
        viewPendingData();
        clearFieldPending();
        
    }//GEN-LAST:event_Pend_DeleteActionPerformed

    private void userInformationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userInformationMouseClicked
        
        //Display the selected user row's data in text fields
        
        DefaultTableModel model = (DefaultTableModel) userInformation.getModel();
        int selectedRowIndex = userInformation.getSelectedRow();
        
        
        user_id.setText(model.getValueAt(selectedRowIndex, 0).toString());
        user_name.setText(model.getValueAt(selectedRowIndex, 1).toString());
        user_email.setText(model.getValueAt(selectedRowIndex, 2).toString());
        user_phone.setText(model.getValueAt(selectedRowIndex, 3).toString());
        user_password.setText(model.getValueAt(selectedRowIndex, 4).toString());
        
        String position = model.getValueAt(selectedRowIndex, 5).toString();
        if(position.equals("Managing staff")){
            jComboBox_position.setSelectedIndex(1);
        }else{
            jComboBox_position.setSelectedIndex(2);
        }
        
        String gender = model.getValueAt(selectedRowIndex, 6).toString();
        if(gender.equals("Male")){
            jRadioButton_male.setSelected(true);
        }else{
            jRadioButton_female.setSelected(true);
        }
        
        
    }//GEN-LAST:event_userInformationMouseClicked

    private void PendingInformationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PendingInformationMouseClicked
        
        //Display the selected pending row's data in text fields
        
        DefaultTableModel model = (DefaultTableModel) PendingInformation.getModel();
        int selectedRowIndex = PendingInformation.getSelectedRow();
        
        
        pend_code.setText(model.getValueAt(selectedRowIndex, 0).toString());
        pend_receiver.setText(model.getValueAt(selectedRowIndex, 1).toString());
        pendi_sender.setText(model.getValueAt(selectedRowIndex, 2).toString());
        pend_send_from.setText(model.getValueAt(selectedRowIndex, 3).toString());
        pend_destination.setText(model.getValueAt(selectedRowIndex, 4).toString());
        pendi_weight_item.setText(model.getValueAt(selectedRowIndex, 6).toString());

    }//GEN-LAST:event_PendingInformationMouseClicked
    
    private void setCurrentDate(JLabel jlabel){
        SimpleDateFormat sdfDate = new SimpleDateFormat("E, MMM dd yyyy | hh:mm:ss aa");
        Timer time = new Timer(500, new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
                jlabel.setText(sdfDate.format(new Date(System.currentTimeMillis())));
            }
        });
        time.setRepeats(true);
        time.start(); 
    }
    
    public void setDashName(String name){
        admin_name.setText(name);
    }
    
        private int number(String fileName){
        //Create a new file and provide path(location) of a file
        String path="src\\File_collection\\";
        String readLines="";
        int totalCounts=0;
        File file = new File(path+fileName);
        try {
            //Since it is in read mode, data is reading from the file 
            BufferedReader br = new BufferedReader(new FileReader(file));
            while((readLines=br.readLine()) != null){
                totalCounts++;
            }
  
        } catch (FileNotFoundException ex) {
            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE,null,ex);
        } catch (IOException ex) {
            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE,null,ex);
        }

        return totalCounts;
    }
    
    public void setNumbers(){ 
        
        userInfo.setText(String.valueOf(number("userInformation.txt")));
        pendingInfo.setText(String.valueOf(number("pendingInfo.txt")));
        deliveryInfo.setText(String.valueOf(number("deliveryInfo.txt")));
    }
    
    private void clearData(JTable jtable){
        
        DefaultTableModel model =  (DefaultTableModel) jtable.getModel();
        
        int removeRows = model.getRowCount();
        
        for (int i = removeRows-1;i>=0;i--){
            model.removeRow(i);
        }
    }
    
    private void clearFieldUser(){
        user_id.setText("");
        user_name.setText("");
        user_password.setText("");
        user_phone.setText("");
        user_email.setText("");
        jComboBox_position.setSelectedIndex(0);
        jRadioButton_male.setSelected(false);
        jRadioButton_female.setSelected(false);
       
    }
    
    private void clearFieldPending(){
        pend_code.setText("");
        pend_destination.setText("");
        pend_receiver.setText("");
        pend_send_from.setText("");
        pendi_sender.setText("");
        pendi_weight_item.setText("");
    }
    
    public void setUserImage(String name){
        String path ="src\\Icons\\";
        User_Image.setIcon(new ImageIcon(path+name+".png"));
    }
    
        
    private void viewUserData() {
    	
    	ArrayList dataList;
    	UserAndProductDao user = new UserAndProductDaoImpl();
    	
    	try {
                dataList = user.viewUser();
                DefaultTableModel dtm = (DefaultTableModel) userInformation.getModel();
                Object[] lines = dataList.toArray();
                for( int i = 0 ; i<lines.length;i++) {
                    String line = lines[i].toString();
                    String [] row = line.split(",");
                    dtm.addRow(row);
            }


            } catch (IOException e) {
                Logger.getLogger(UserDashboard.class.getName()).log(Level.SEVERE, null, e);
            }	
    }
    
 private void viewPendingData() {
    	
    ArrayList dataList;
    UserAndProductDao user = new UserAndProductDaoImpl();

    try {
            dataList = user.viewPending();
            DefaultTableModel dtm = (DefaultTableModel) PendingInformation.getModel();
            Object[] lines = dataList.toArray();
            for( int i = 0 ; i<lines.length;i++) {
                    String line = lines[i].toString();
                    String [] row = line.split(",");
                    dtm.addRow(row);
        }


        } catch (IOException e) {

                Logger.getLogger(UserDashboard.class.getName()).log(Level.SEVERE, null, e);
        }
	
    }
 
 private void viewDeliveryData() {
 	
    ArrayList dataList;
    UserAndProductDao user = new UserAndProductDaoImpl();

    try {
            dataList = user.viewDelivery();
            DefaultTableModel dtm = (DefaultTableModel) deliveryInformation.getModel();
            Object[] lines = dataList.toArray();
            for( int i = 0 ; i<lines.length;i++) {
                    String line = lines[i].toString();
                    String [] row = line.split(",");
                    dtm.addRow(row);
            }


        } catch (IOException e) {

                Logger.getLogger(UserDashboard.class.getName()).log(Level.SEVERE, null, e);
        }	
 }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Dash_Delivery;
    private javax.swing.JLabel Dash_Pending;
    private javax.swing.JLabel Dash_Report;
    private javax.swing.JLabel Dash_User;
    private javax.swing.JLabel Dashboard;
    private javax.swing.JButton Pend_Add;
    private javax.swing.JButton Pend_Delete;
    private javax.swing.JButton Pend_Update;
    private javax.swing.JTable PendingInformation;
    private javax.swing.JButton User_Add;
    private javax.swing.JButton User_Delete;
    private javax.swing.JLabel User_Image;
    private javax.swing.JButton User_Update;
    private javax.swing.JLabel admin_name;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel dash_date;
    private javax.swing.JPanel dashboardPanel;
    private javax.swing.JLabel deliveryInfo;
    private javax.swing.JTable deliveryInformation;
    private javax.swing.JPanel deliveryPending;
    private javax.swing.JLabel delivery_date;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox_position;
    private javax.swing.JLabel jLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_salesProduct;
    private javax.swing.JLabel jLabel_salesProduct1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel_greenBar;
    private javax.swing.JPanel jPanel_orangeBar;
    private javax.swing.JPanel jPanel_redBar;
    private javax.swing.JPanel jPanel_redBar1;
    private javax.swing.JRadioButton jRadioButton_female;
    private javax.swing.JRadioButton jRadioButton_male;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField pend_code;
    private javax.swing.JTextField pend_destination;
    private javax.swing.JTextField pend_receiver;
    private javax.swing.JTextField pend_send_from;
    private javax.swing.JTextField pendi_sender;
    private javax.swing.JTextField pendi_weight_item;
    private javax.swing.JLabel pendingInfo;
    private javax.swing.JPanel pendingPanel;
    private javax.swing.JLabel pending_date;
    private javax.swing.JLabel reportInfo;
    private javax.swing.JLabel userInfo;
    private javax.swing.JTable userInformation;
    private javax.swing.JPanel userPanel;
    private javax.swing.JLabel user_date;
    private javax.swing.JTextField user_email;
    private javax.swing.JTextField user_id;
    private javax.swing.JTextField user_name;
    private javax.swing.JTextField user_password;
    private javax.swing.JTextField user_phone;
    // End of variables declaration//GEN-END:variables
}
