
package co.system.orderManagementForm;

import co.system.LoginForm.LoginForm;
import co.system.Dao.UserAndProductDao;
import co.system.Dao.UserAndProductDaoImpl;
import co.system.bll.UserAndProduct;
import co.system.userManagementForm.UserDashboard;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

public class Product_Status extends javax.swing.JFrame {


    public Product_Status() {
        initComponents();
        setLocationRelativeTo(null);
        setCurrentDate();
        viewDeliveryData();
        viewPendingData();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_deliveryInformation1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_pendingInformation1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton_delivered = new javax.swing.JButton();
        jButton_delivered1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel_adminName = new javax.swing.JLabel();
        jLabel_currentDate = new javax.swing.JLabel();
        jLabel_image = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 102, 0));

        jTable_deliveryInformation1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tracking code", "Receiver", "Sender", "Send From", "Destination", "Date", "Weight/Item"
            }
        ));
        jScrollPane1.setViewportView(jTable_deliveryInformation1);

        jTable_pendingInformation1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tracking code", "Receiver", "Sender", "Send From", "Destination", "Date", "Weight/Item"
            }
        ));
        jTable_pendingInformation1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_pendingInformation1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable_pendingInformation1);

        jLabel3.setBackground(new java.awt.Color(255, 153, 0));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Delivery status");
        jLabel3.setOpaque(true);

        jLabel4.setBackground(new java.awt.Color(255, 153, 0));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Pending status");
        jLabel4.setOpaque(true);

        jButton_delivered.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_delivered.setText("Delivered");
        jButton_delivered.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_deliveredActionPerformed(evt);
            }
        });

        jButton_delivered1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_delivered1.setText("Logout");
        jButton_delivered1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_delivered1ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 153, 0));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 34)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Logo.png"))); // NOI18N
        jLabel2.setText("LOGO");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Product status");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Welcom");

        jLabel_adminName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_adminName.setText("Admin");

        jLabel_currentDate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_currentDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_currentDate.setText("Date");

        jLabel_image.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                .addGap(236, 236, 236)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel_currentDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(173, 173, 173)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel_image, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_adminName, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 41, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel_currentDate))
                    .addComponent(jLabel_image, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel_adminName))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 850, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton_delivered, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(jButton_delivered1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_delivered, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton_delivered1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private String tracking_codes="";
    private String receiver="";
    private String sender="";
    private String send_from="";
    private String destination="";
    private String date="";
    private String weight_items="";
    
    
    private void jButton_delivered1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_delivered1ActionPerformed
        LoginForm login = new LoginForm();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton_delivered1ActionPerformed

    private void jTable_pendingInformation1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_pendingInformation1MouseClicked
         DefaultTableModel model = (DefaultTableModel) jTable_pendingInformation1.getModel();
        int selectedRowIndex = jTable_pendingInformation1.getSelectedRow();
        
        tracking_codes=(model.getValueAt(selectedRowIndex, 0).toString());
        receiver=(model.getValueAt(selectedRowIndex, 1).toString());
        sender=(model.getValueAt(selectedRowIndex, 2).toString());
        send_from=(model.getValueAt(selectedRowIndex, 3).toString());
        destination=(model.getValueAt(selectedRowIndex, 4).toString());
        date = (model.getValueAt(selectedRowIndex, 5).toString());
        weight_items = (model.getValueAt(selectedRowIndex, 6).toString());
    }//GEN-LAST:event_jTable_pendingInformation1MouseClicked
    
    private void clearData(JTable jtable){
        
        DefaultTableModel model =  (DefaultTableModel) jtable.getModel();
        
        int removeRows = model.getRowCount();
        
        for (int i = removeRows-1;i>=0;i--){
            model.removeRow(i);
        }
    }
    
    private void jButton_deliveredActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_deliveredActionPerformed
        
        //Transfer the selected row's data of pending into delivery
        
        UserAndProductDao userss = new UserAndProductDaoImpl();
        UserAndProduct user = new UserAndProduct();
        
        if(tracking_codes.equals("")|| receiver.equals("")
                || sender.equals("")|| send_from.equals("")
                || destination.equals("")|| date.equals("")
                || weight_items.equals("")){
        
            JOptionPane.showMessageDialog(null, "Select a row to swift into delivered.");
    }else{
           try {
               
            int ids = Integer.parseInt(tracking_codes);
            user.setTracking_code(ids);
            user.setReceiver(receiver);
            user.setSender(sender);
            user.setSend_from(send_from);
            user.setDestination(destination);
            user.setDate(date);
            user.setWeight_item(weight_items);
            
            userss.deleteProduct(user);
            userss.addProduct(user, "deliveryInfo.txt");
            
        } catch (IOException ex) {
            Logger.getLogger(Product_Status.class.getName()).log(Level.SEVERE, null, ex);
        } 
        }
       
        clearData(jTable_pendingInformation1);
        clearData(jTable_deliveryInformation1);
        viewDeliveryData();
        viewPendingData();

        
    }//GEN-LAST:event_jButton_deliveredActionPerformed
    
     public void setUserName(String name){
        jLabel_adminName.setText(name);
    }
     
    private void setCurrentDate(){
        Date date = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("E, MMM dd yyyy | hh:mm aa");
        String current_date= sdf.format(date);
        jLabel_currentDate.setText(current_date);
    }
    
    public void setUserImage(String imageName){
        String path = "C:\\Users\\SUMAN\\Documents\\"
                + "NetBeansProjects\\JframeTesting\\src\\Icons\\";
        jLabel_image.setIcon(new ImageIcon(path+imageName+".png"));
    }
    
     private void viewPendingData() {
    	
    ArrayList dataList;
    UserAndProductDao user = new UserAndProductDaoImpl();

    try {
            dataList = user.viewPending();
            DefaultTableModel dtm = (DefaultTableModel) jTable_pendingInformation1.getModel();
            Object[] lines = dataList.toArray();
            for( int i = 0 ; i<lines.length;i++) {
                    String line = lines[i].toString();
                    String [] row = line.split(",");
                    dtm.addRow(row);
        }


        } catch (IOException e) {

                Logger.getLogger(UserDashboard.class.getName()).log(Level.SEVERE, null, e);
        }
	
    }
 
 private void viewDeliveryData() {
 	
    ArrayList dataList;
    UserAndProductDao user = new UserAndProductDaoImpl();

    try {
            dataList = user.viewDelivery();
            DefaultTableModel dtm = (DefaultTableModel) jTable_deliveryInformation1.getModel();
            Object[] lines = dataList.toArray();
            for( int i = 0 ; i<lines.length;i++) {
                    String line = lines[i].toString();
                    String [] row = line.split(",");
                    dtm.addRow(row);
            }


        } catch (IOException e) {

                Logger.getLogger(UserDashboard.class.getName()).log(Level.SEVERE, null, e);
        }	
 }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Product_Status.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Product_Status.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Product_Status.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Product_Status.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Product_Status().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_delivered;
    private javax.swing.JButton jButton_delivered1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel_adminName;
    private javax.swing.JLabel jLabel_currentDate;
    private javax.swing.JLabel jLabel_image;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable_deliveryInformation1;
    private javax.swing.JTable jTable_pendingInformation1;
    // End of variables declaration//GEN-END:variables
}
